## 2.3 Linear Algebra

### 2.3.1 Scalars

In [1]:
import torch

x = torch.tensor(3.0)
y = torch.tensor(2.0)

x + y, x * y, x / y, x**y

(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

### 2.3.2 Vectors

In [2]:
x = torch.arange(3)
x

tensor([0, 1, 2])

In [3]:
x[2]

tensor(2)

In [4]:
len(x)

3

In [5]:
x.shape

torch.Size([3])

### 2.3.3 Matrices

In [6]:
A = torch.arange(6).reshape(3, 2)
A

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [7]:
A.T

tensor([[0, 2, 4],
        [1, 3, 5]])

In [8]:
A = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
A == A.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

### 2.3.4 Tensors

In [9]:
torch.arange(24).reshape(2, 3, 4)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

### 2.3.5 Basic Properties of Tensor Arithmetic

In [10]:
A = torch.arange(6, dtype=torch.float32).reshape(2, 3)
B = A.clone()  # Assign a copy of A to B by allocating new memory
A, A + B

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[ 0.,  2.,  4.],
         [ 6.,  8., 10.]]))

In [ ]:
A * B

tensor([[ 0.,  1.,  4.],
        [ 9., 16., 25.]])

In [12]:
a = 2
X = torch.arange(24).reshape(2, 3, 4)
a + X, (a * X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

### 2.3.6 Reduction

In [13]:
x = torch.arange(3, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2.]), tensor(3.))

In [14]:
A.shape, A.sum()

(torch.Size([2, 3]), tensor(15.))

In [15]:
A.shape, A.sum(axis=0).shape

(torch.Size([2, 3]), torch.Size([3]))

In [16]:
A.shape, A.sum(axis=1).shape

(torch.Size([2, 3]), torch.Size([2]))

In [17]:
A.sum(axis=[0, 1]) == A.sum()  # Same as A.sum()

tensor(True)

In [18]:
A.mean(), A.sum() / A.numel()

(tensor(2.5000), tensor(2.5000))

In [19]:
A.mean(axis=0), A.sum(axis=0) / A.shape[0]

(tensor([1.5000, 2.5000, 3.5000]), tensor([1.5000, 2.5000, 3.5000]))

### 2.3.7 Non-Reduction Sum

In [20]:
sum_A = A.sum(axis=1, keepdims=True)
sum_A, sum_A.shape

(tensor([[ 3.],
         [12.]]),
 torch.Size([2, 1]))

In [21]:
A / sum_A

tensor([[0.0000, 0.3333, 0.6667],
        [0.2500, 0.3333, 0.4167]])

In [22]:
A.cumsum(axis=0)

tensor([[0., 1., 2.],
        [3., 5., 7.]])

### 2.3.8 Dot Products

In [23]:
y = torch.ones(3, dtype = torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2.]), tensor([1., 1., 1.]), tensor(3.))

In [24]:
torch.sum(x * y)

tensor(3.)

### 2.3.9 Matrix-Vector Products

In [25]:
A.shape, x.shape, torch.mv(A, x), A@x

(torch.Size([2, 3]), torch.Size([3]), tensor([ 5., 14.]), tensor([ 5., 14.]))

### 2.3.10 Matrix-Matrix Multiplication

In [26]:
"""
A = [[0 1 2]
     [3 4 5]]

B = [[1 1 1 1]
     [1 1 1 1]
     [1 1 1 1]]

AB = [[0*1+1*1+2*1 0*1+1*1+2*1 0*1+1*1+2*1 0*1+1*1+2*1]
      [3*1+4*1+5*1 3*1+4*1+5*1 3*1+4*1+5*1 3*1+4*1+5*1]]
   = [[3 3 3 3]
      [12 12 12 12]]
"""

B = torch.ones(3, 4)
torch.mm(A, B), A@B

(tensor([[ 3.,  3.,  3.,  3.],
         [12., 12., 12., 12.]]),
 tensor([[ 3.,  3.,  3.,  3.],
         [12., 12., 12., 12.]]))

### 2.3.11 Norms

In [30]:
# l2 norm
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

In [28]:
# l1 norm
torch.abs(u).sum()

tensor(7.)

In [31]:
# Frobenius norm
torch.norm(torch.ones((4, 9)))

tensor(6.)